### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'stickers' in Telegram bot

### ISSUE THREAD

**Issue by Eugene-Lam** [Eugene-Lam/cityu-bot#8]
According to ChatGPT

> This is a Python error message that indicates an AttributeError caused by a coroutine that is missing the 'stickers' attribute. It seems that in the file '/usr/src/app/./main.py' on line 287, there is an asynchronous function named 'rich' that is trying to access the 'stickers' attribute of a List[Sticker], but the attribute is not available on the object.

The error message also shows a RuntimeWarning, suggesting that the coroutine 'ExtBot.get_sticker_set' was never awaited. This means that the coroutine was not properly called with the 'await' keyword, causing the function to not complete before moving on to the next step in the code.

To fix this error, you should make sure that the 'await' keyword is properly used when calling asynchronous functions that return a coroutine. In this case, you may need to modify the 'rich' function to properly await the 'get_sticker_set' coroutine, or check if the function call returns a valid object with the 'stickers' attribute.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/usr/src/app/./main.py", line 287, in rich
    sticker_set: List[Sticker] = await context.bot.get_sticker_set("line_276090076_by_moe_sticker_bot").stickers
AttributeError: 'coroutine' object has no attribute 'stickers'
/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py:1114: RuntimeWarning: coroutine 'ExtBot.get_sticker_set' was never awaited
  if await self.process_error(update=update, error=exc):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

**Comment by Eugene-Lam** [comment]
ChatGPT:
To fix this error, you need to make sure that you are properly awaiting the coroutine returned by the get_sticker_set method in the context.bot object.

Here is an example of how you can modify the code to fix the error:

```python
async def rich(update: Update, context: CallbackContext):
    sticker_set = await context.bot.get_sticker_set("line_276090076_by_moe_sticker_bot")
    stickers = sticker_set.stickers  # access the 'stickers' attribute after awaiting the coroutine
    # do something with the stickers list
```
In this example, the get_sticker_set coroutine is first awaited and its return value is stored in the sticker_set variable. The stickers attribute is then accessed after the coroutine has completed, allowing you to access the list of stickers without raising an AttributeError.

By properly awaiting the coroutine before accessing its attributes, you can avoid the AttributeError: 'coroutine' object has no attribute 'stickers' error.
